### ISSUE TITLE
Error: "Sorry, relation #2688911 could not be found." on Nominatum Search

### ISSUE THREAD

**Issue by JaimeLynSchatz** [OpenHistoricalMap/ohm-website#17]
@muninn: I thought perhaps that I broke something in my branch, but I ran the search on the live version of the website and I get the same error. Should I ignore for now or run this down?
![screenshot](http://jaimelynschatz.github.io/nominatum_error.png)

**Comment by GWHAThistory** [comment]
We should probably use a different geocoder with just placenames until we get the database more populated... or, we could hook up Nominatim, but it wouldn't really point anywhere yet.

**Comment by rwelty1889** [comment]
On 6/9/15 5:07 PM, Jeff Meyer wrote:
>
> We should probably use a different geocoder with just placenames until
> we get the database more populated... or, we could hook up Nominatim,
> but it wouldn't really point anywhere yet.
>
it might be fun to try setting up Pelias (the mapzen geocoder).

richard

-- 
rwelty@averillpark.net
 Averill Park Networking - GIS & IT Consulting
 OpenStreetMap - PostgreSQL - Linux
 Java - Web Applications - Search

**Comment by GWHAThistory** [comment]
Good suggestion ref: Pelias... 
https://github.com/pelias/pelias

**Comment by Abbe98** [comment]
The OHM website currently use the OSM Nominatim instance, returning element ids from OpenStreetMap, witch do not exist in OHM...

I guess the fastest solution is to just point Nominatim to OHM?

**Comment by rwelty1889** [comment]
On 6/10/15 6:08 AM, Albin Larsson wrote:
>
> The OHM website currently use the OSM Nominatim instance, returning
> element ids from OpenStreetMap, witch do not exist in OHM...
>
> I guess the fastest solution is to just point Nominatim to OHM?
>
i think we would need to install our own Nominatim instance. which
brings up the question of whether Nominatim is really the geocoder
we want. that's why i brought up Pelias, an alternative that has some
cool features. there are others, there's been a lot of activity in
OSM geocoding over the past 2 years.

richard

-- 
rwelty@averillpark.net
 Averill Park Networking - GIS & IT Consulting
 OpenStreetMap - PostgreSQL - Linux
 Java - Web Applications - Search

**Comment by GWHAThistory** [comment]
Agreed with the inclination to try with Pelias instead of Nominatim, if
possible.

On Wed, Jun 10, 2015 at 4:18 AM, Richard Welty <notifications@github.com>
wrote:

> On 6/10/15 6:08 AM, Albin Larsson wrote:
> >
> > The OHM website currently use the OSM Nominatim instance, returning
> > element ids from OpenStreetMap, witch do not exist in OHM...
> >
> > I guess the fastest solution is to just point Nominatim to OHM?
> >
> i think we would need to install our own Nominatim instance. which
> brings up the question of whether Nominatim is really the geocoder
> we want. that's why i brought up Pelias, an alternative that has some
> cool features. there are others, there's been a lot of activity in
> OSM geocoding over the past 2 years.
>
> richard
>
> --
> rwelty@averillpark.net
> Averill Park Networking - GIS & IT Consulting
> OpenStreetMap - PostgreSQL - Linux
> Java - Web Applications - Search
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenHistoricalMap/ohm-website/issues/17#issuecomment-110704384>
> .
>



-- 
Jeff Meyer
Global World History Atlas
www.gwhat.org
jeff@gwhat.org
206-676-2347

OpenStreetMap: Mapping with a Human Touch
osm: Open Historical Map (OHM)
<http://wiki.openstreetmap.org/wiki/Open_Historical_Map> / my OSM user page
<http://www.openstreetmap.org/user/jeffmeyer>
t: @GWHAThistory <https://twitter.com/GWHAThistory> / @OpenHistMap
f: GWHAThistory <https://www.facebook.com/GWHAThistory>

**Comment by rwarren2** [comment]
Obsolete. Closing.
